on:
   push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'mona/octocat'
      - 'releases/**'

    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'mona/octocat'
      - 'releases/**-alpha'

jobs:
      firstjob:
            runs-on: ubuntu-latest
            steps:
                    - name: checking out the code
                      uses: actions/acheckout@v3
                    - name: sample script
                      run: echo "githubactions"
